---
- hosts: sonar
  become: yes
  tasks:
  - name: Install PIP
    yum:
      name: python-pip
      state: present
  - name: Install lxml
    pip:
      name: lxml
  - name: Remove Older JARS
    shell: rm -f /opt/gs-spring-boot*.jar
  - name: download artifacts
    maven_artifact:
      group_id: org.springframework
      artifact_id: gs-spring-boot
      repository_url: http://54.82.212.223:8081/repository/maven-releases/
      version: "{{ version }}"
      username: "{{ lookup('aws_secret', 'nexus_user') }}"
      password: "{{ lookup('aws_secret', 'nexus_password') }}"
      dest: /opt
